### ISSUE TITLE
Requesting the name pyphase on Read the Docs

### ISSUE THREAD

**Issue by davidfischer** [sluenenglish/pyphase#2]
Another user has requested the name pyphase on Read the Docs which is taken by this project (which seems abandoned). Would you be willing to give up the name of the project on Read the Docs to another maintainer by deleting or renaming your project?

Ref: https://github.com/readthedocs/readthedocs.org/issues/7457

**Comment by sluenenglish** [comment]
Hi David, I've deleted the project so the name can be used :+1:
